version: '3'

services:
  mysql:
    image: mysql
    container_name: mysqlAngularSpring
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medical
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/
    ports:
      - "3308:3306"

volumes:
  container-volume: